require("dotenv").config();

const {
  REACT_APP_BITMEX_URL_TN,
  REACT_APP_BITMEX_URL_MN,
  REACT_APP_API_KEY_TN,
  REACT_APP_API_KEY_MN,
  REACT_APP_API_SECRET_MN,
  REACT_APP_API_SECRET_TN,
} = process.env;

module.exports = {
  REACT_APP_BITMEX_URL_TN,
  REACT_APP_BITMEX_URL_MN,
  REACT_APP_API_KEY_TN,
  REACT_APP_API_KEY_MN,
  REACT_APP_API_SECRET_MN,
  REACT_APP_API_SECRET_TN,
};
